package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"food_ordering_coordination_system/graph/model"
	"github.com/google/uuid"
	"sync"
)

var (
	foodOrders []*model.FoodOrder
	mu         sync.Mutex
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.NewOrder) (*model.FoodOrder, error) {
	items := make([]*model.FoodItem, len(input.Items))
	var totalPrice float64

	for i, itemInput := range input.Items {
		item := &model.FoodItem{
			ID:       uuid.New().String(),
			Name:     itemInput.Name,
			Quantity: itemInput.Quantity,
			Price:    itemInput.Price,
		}
		items[i] = item
		totalPrice += itemInput.Price * float64(itemInput.Quantity)
	}

	order := &model.FoodOrder{
		ID:            uuid.New().String(),
		MemberID:      input.MemberID,
		Items:         items,
		Status:        "PLACED",
		TotalPrice:    totalPrice,
		DeliveryNotes: input.DeliveryNotes,
	}

	mu.Lock()
	defer mu.Unlock()
	foodOrders = append(foodOrders, order)
	return order, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.FoodOrder, error) {
	mu.Lock()
	defer mu.Unlock()
	ordersCopy := make([]*model.FoodOrder, len(foodOrders))
	copy(ordersCopy, foodOrders)
	return ordersCopy, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
