// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FoodItem struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type FoodOrder struct {
	ID            string      `json:"id"`
	MemberID      string      `json:"memberId"`
	Items         []*FoodItem `json:"items"`
	Status        string      `json:"status"`
	TotalPrice    float64     `json:"totalPrice"`
	DeliveryNotes *string     `json:"deliveryNotes,omitempty"`
}

type Mutation struct {
}

type NewItem struct {
	Name     string  `json:"name"`
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type NewOrder struct {
	MemberID      string     `json:"memberId"`
	Items         []*NewItem `json:"items"`
	DeliveryNotes *string    `json:"deliveryNotes,omitempty"`
}

type Query struct {
}
