package main

import (
	"context"

	// This package is generated by Dagger.
	// Run `dagger develop` to generate it locally.
	"dagger/food-ordering-coordination-system/internal/dagger"
)

type FoodOrderingCoordinationSystem struct{}

// BuildFrontend builds the Next.js frontend.
func (m *FoodOrderingCoordinationSystem) BuildFrontend(
	ctx context.Context,
	// Source directory
	source *dagger.Directory,
) *dagger.Directory {
	return dagger.Dag().Container().
		From("node:20").
		WithExec([]string{"corepack", "enable"}).
		WithDirectory("/src", source, dagger.ContainerWithDirectoryOpts{
			Exclude: []string{"node_modules", ".next"},
		}).
		WithWorkdir("/src").
		WithExec([]string{"pnpm", "install"}).
		WithExec([]string{"pnpm", "run", "build"}).
		Directory("/src/.next")
}

// BuildBackend builds the Go backend.
func (m *FoodOrderingCoordinationSystem) BuildBackend(
	ctx context.Context,
	// Source directory
	source *dagger.Directory,
) *dagger.File {
	return dagger.Dag().Container().
		From("golang:1.24").
		WithDirectory("/src", source, dagger.ContainerWithDirectoryOpts{
			Exclude: []string{"node_modules", ".next", "api/server"},
		}).
		WithWorkdir("/src/api").
		WithExec([]string{"go", "mod", "download"}).
		WithExec([]string{"go", "build", "-o", "server", "./main.go"}).
		File("/src/api/server")
}

// TestBackend runs the Go backend tests.
// It requires access to the host Docker socket for testcontainers.
func (m *FoodOrderingCoordinationSystem) TestBackend(
	ctx context.Context,
	// Source directory
	source *dagger.Directory,
) (string, error) {
	return dagger.Dag().Container().
		From("golang:1.24").
		WithDirectory("/src", source, dagger.ContainerWithDirectoryOpts{
			Exclude: []string{"node_modules", ".next", "api/server"},
		}).
		WithWorkdir("/src/api").
		WithUnixSocket("/var/run/docker.sock", dagger.Dag().Host().UnixSocket("/var/run/docker.sock")).
		WithEnvVariable("DOCKER_HOST", "unix:///var/run/docker.sock").
		WithExec([]string{"go", "mod", "download"}).
		WithExec([]string{"go", "test", "./..."}).
		Stdout(ctx)
}
